server:
  port: ${PORT:9002}

spring:
  application:
    name: cam-recorder
  mustache.check-template-location: false
  jpa:
    defer-datasource-initialization: true # TODO remove

logging:
  level:
    ROOT: INFO
    org.atmosphere: WARN
    com.giraone.streaming: DEBUG
  pattern:
    dateformat: 'yyyy-MM-dd HH:mm:ss.SSS,Europe/Berlin'

management:
  endpoints:
    web:
      exposure:
        # health,prometheus is needed; the others are for troubleshooting
        include: 'health,metrics,prometheus,loggers'

vaadin:
   # Launch the default browser when starting the application in development mode
  launch-browser: true
  # To improve the performance during development.
  # For more information https://vaadin.com/docs/flow/spring/tutorial-spring-configuration.html#special-configuration-parameters
  whitelisted-packages: com.vaadin,org.vaadin,com.giraone
  # By-pass these URLs from Vaadin
  exclude-urls: '/api/**'
  # servlet.productionMode: true